backend:
  # TODO
  accessToken: ""
  # TODO
  webdav: false
  performance:
    # Whiteboard information broadcasting frequency (in Hz i.e. /s)
    # => diminishing this will result in more latency
    whiteboardInfoBroadcastFreq: 1

frontend:
  # When a whiteboard is loading in a client
  onWhiteboardLoad:
    # should an (editable) whiteboard be started in read-only mode by default
    setReadOnly: false
    # should the whiteboard info be displayed by default
    displayInfo: false
  # Show smallest screen indicator
  showSmallestScreenIndicator: true
  performance:
    pointerEventsThrottling:
      - fromNbUser: 0
        minDistDelta: 1
        maxFreq: 30
    refreshInfoFreq: 5
